#! /usr/bin/bash
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
python TMD+tw3_replicas_new.py
