#! /usr/bin/bash
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
python TMD+tw3_replicas.py
